version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - run: mkdir reports
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Start Selenium
          command: |
            java -jar node_modules/selenium-server-standalone/index.jar -log reports/selenium.log
          background: true
      - run:
          name: Create a production build
          command: |
            yarn build
      - run:
          name: Run server
          command: |
            yarn serve
          background: true
      - run:
          name: Wait for server
          command: yarn wait-on http://localhost:3000 -t 10000
      - run: yarn test --testPathIgnorePatterns src/shared/OpenFiscaAPIClient/OpenFiscaAPIClient.test.js
      - store_artifacts:
          path: ./reports/failure_screenshots/
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
